<?php

namespace App\Traits;

use Illuminate\Support\Fluent;

trait MontarForm
{
    public function montarForm($tipo, $value = null)
    {
        return match ($tipo) {
            'clientes' => $this->montarFormCliente($value),
            'empresas' => $this->montarFormEmpresa($value),
            'veiculos' => $this->montarFormVeiculos($value),
            'motoristas' => $this->montarFormMotoristas($value),
            'especializacao' => $this->montarFormEspecializacao($value),
            'adicionais' => $this->montarFormAdicionais($value),
            'categorias' => $this->montarFormCategorias($value),
            'categorias-servicos' => $this->montarFormCategoriasServicos($value),
            'segurancas' => $this->montarFormSegurancas($value),
            'servicos' => $this->montarFormServicos($value),
            'orcamentos' => $this->montarFormOrcamento($value),
            'os' => $this->montarFormOS($value),
        };
    }

    private function montarFormCliente($value = null)
    {
        $data = new Fluent([
            'pageInfo' => [
                'title' => $value ? 'Editar cliente' : 'Cadastrar cliente',
                'form_action' => '',
                'form_method' => '',
                'label_button' => $value ? 'Editar cliente' : 'Cadastrar cliente',
                //Aqui a ideia é passar um array com todos os dados bancários e montar ele no formBank
                'dados_bancarios' => $value['dados_bancarios'] ?? true,
                'cadastro_contatos' => true,
                'cadastro_adicionais' => false,
                'cadastro_especializacoes' => false,
                'cadastro_servicos' => true,
            ],
            'sessions' => [
                'Dados da Empresa' => [
                    'cpf' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-6',
                        'label' => 'CPF/CNPJ',
                        'type' => 'text',
                        'placeholder' => '00.000.000/0001-00',
                        'maxlenghtRoute' => 18,
                        'required' => false,
                        'id' => 'cpfcnpj',
                        'name' => 'cpfcnpj',
                        'function' => false,
                        'value' => $value['cpf'] ?? null,
                    ],
                    'apelido' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-6',
                        'label' => 'Apelido',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 50,
                        'required' => false,
                        'id' => 'apelido',
                        'name' => 'apelido',
                        'function' => false,
                        'value' => $value['apelido'] ?? null,
                    ],
                    'razao_social' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-6',
                        'label' => 'Razão Social',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 70,
                        'required' => false,
                        'id' => 'razao',
                        'name' => 'razao',
                        'function' => false,
                        'value' => $value['razao_social'] ?? null,
                    ],
                    'nome_fantasia' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-6',
                        'label' => 'Nome Fantasia',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 70,
                        'required' => false,
                        'id' => 'nome_fantasia',
                        'name' => 'nome_fantasia',
                        'function' => false,
                        'value' => $value['nome_fantasia'] ?? null,
                    ],
                    'cep' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-3',
                        'label' => 'CEP',
                        'type' => 'number',
                        'placeholder' => '00000-000',
                        'maxlenghtRoute' => 9,
                        'required' => false,
                        'id' => 'cep',
                        'name' => 'cep',
                        'function' => [
                            'type' => 'onblur',
                            'name' => 'pesquisaCep(this.value)',
                        ],
                        'value' => $value['cep'] ?? null,
                    ],
                    'logradouro' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-7',
                        'label' => 'Logradouro',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 50,
                        'required' => false,
                        'id' => 'logradouro',
                        'name' => 'logradouro',
                        'function' => false,
                        'value' => $value['logradouro'] ?? null,
                    ],
                    'numero' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-2',
                        'label' => 'Número',
                        'type' => 'number',
                        'placeholder' => '123',
                        'maxlenghtRoute' => 10,
                        'required' => false,
                        'id' => 'numero',
                        'name' => 'numero',
                        'function' => false,
                        'value' => $value['numero'] ?? null,
                    ],
                    'bairro' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-4',
                        'label' => 'Bairro',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 30,
                        'required' => false,
                        'id' => 'bairro',
                        'name' => 'bairro',
                        'function' => false,
                        'value' => $value['bairro'] ?? null,
                    ],
                    'cidade' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-4',
                        'label' => 'Cidade',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 40,
                        'required' => false,
                        'id' => 'cidade',
                        'name' => 'cidade',
                        'function' => false,
                        'value' => $value['cidade'] ?? null,
                    ],
                    'estado' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-2',
                        'label' => 'Estado',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 2,
                        'required' => false,
                        'id' => 'estado',
                        'name' => 'estado',
                        'function' => false,
                        'value' => $value['estado'] ?? null,
                    ],
                    'pais' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-2',
                        'label' => 'País',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 15,
                        'required' => false,
                        'placeholder' => '',
                        'id' => 'pais',
                        'name' => 'pais',
                        'function' => false,
                        'value' => $value['pais'] ?? null,
                    ],
                ],
                'Contatos da Empresa' => [
                    'phone' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-4',
                        'label' => 'Telefone empresarial',
                        'type' => 'number',
                        'placeholder' => '(00)0000-00000',
                        'maxlenghtRoute' => 14,
                        'required' => false,
                        'id' => 'phone',
                        'name' => 'phone',
                        'function' => false,
                    ],
                    'email' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-8',
                        'label' => 'E-mail empresarial',
                        'type' => 'email',
                        'placeholder' => 'contato@b13company.com',
                        'maxlenghtRoute' => 70,
                        'required' => false,
                        'id' => 'email',
                        'name' => 'email',
                        'function' => false,
                    ],
                ],
            ],
        ]);
        return $data;
    }

    private function montarFormEmpresa($value = null)
    {
        $data = new Fluent([
            'pageInfo' => [
                'title' => $value ? 'Editar empresa' : 'Cadastrar empresa',
                'form_action' => '',
                'form_method' => '',
                'label_button' => $value ? 'Editar empresa' : 'Cadastrar empresa',
                'dados_bancarios' => true,
                'cadastro_contatos' => false,
                'cadastro_adicionais' => false,
                'cadastro_especializacoes' => false,
                'cadastro_servicos' => true,
            ],
            'sessions' => [
                'Dados da Empresa' => [
                    'cpf' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-6',
                        'label' => 'CPF/CNPJ',
                        'type' => 'text',
                        'placeholder' => '00.000.000/0001-00',
                        'maxlenghtRoute' => 18,
                        'required' => false,
                        'id' => 'cpfcnpj',
                        'name' => 'cpfcnpj',
                        'function' => false,
                        'value' => $value['cpf'] ?? null,
                    ],
                    'apelido' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-6',
                        'label' => 'Apelido',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 50,
                        'required' => false,
                        'id' => 'apelido',
                        'name' => 'apelido',
                        'function' => false,
                        'value' => $value['apelido'] ?? null,
                    ],
                    'razao_social' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-6',
                        'label' => 'Razão Social',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 70,
                        'required' => false,
                        'id' => 'razao',
                        'name' => 'razao',
                        'function' => false,
                        'value' => $value['razao_social'] ?? null,
                    ],
                    'nome_fantasia' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-6',
                        'label' => 'Nome Fantasia',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 70,
                        'required' => false,
                        'id' => 'nome_fantasia',
                        'name' => 'nome_fantasia',
                        'function' => false,
                        'value' => $value['nome_fantasia'] ?? null,
                    ],
                    'cep' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-3',
                        'label' => 'CEP',
                        'type' => 'number',
                        'placeholder' => '00000-000',
                        'maxlenghtRoute' => 9,
                        'required' => false,
                        'id' => 'cep',
                        'name' => 'cep',
                        'function' => [
                            'type' => 'onChange',
                            'name' => 'pesquisaCep()',
                        ],
                        'value' => $value['cep'] ?? null,
                    ],
                    'logradouro' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-7',
                        'label' => 'Logradouro',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 50,
                        'required' => false,
                        'id' => 'logradouro',
                        'name' => 'logradouro',
                        'function' => false,
                        'value' => $value['logradouro'] ?? null,
                    ],
                    'numero' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-2',
                        'label' => 'Número',
                        'type' => 'number',
                        'placeholder' => '123',
                        'maxlenghtRoute' => 10,
                        'required' => false,
                        'id' => 'numero',
                        'name' => 'numero',
                        'function' => false,
                        'value' => $value['numero'] ?? null,
                    ],
                    'bairro' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-4',
                        'label' => 'Bairro',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 30,
                        'required' => false,
                        'id' => 'bairro',
                        'name' => 'bairro',
                        'function' => false,
                        'value' => $value['bairro'] ?? null,
                    ],
                    'cidade' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-4',
                        'label' => 'Cidade',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 40,
                        'required' => false,
                        'id' => 'cidade',
                        'name' => 'cidade',
                        'function' => false,
                        'value' => $value['cidade'] ?? null,
                    ],
                    'estado' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-2',
                        'label' => 'Estado',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 2,
                        'required' => false,
                        'id' => 'estado',
                        'name' => 'estado',
                        'function' => false,
                        'value' => $value['estado'] ?? null,
                    ],
                    'pais' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-2',
                        'label' => 'País',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 15,
                        'required' => false,
                        'placeholder' => '',
                        'id' => 'pais',
                        'name' => 'pais',
                        'function' => false,
                        'value' => $value['pais'] ?? null,
                    ],
                ],
                'Contatos da Empresa' => [
                    'phone' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-4',
                        'label' => 'Telefone empresarial',
                        'type' => 'number',
                        'placeholder' => '(00)0000-00000',
                        'maxlenghtRoute' => 14,
                        'required' => false,
                        'id' => 'phone',
                        'name' => 'phone',
                        'function' => false,
                    ],
                    'email' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-8',
                        'label' => 'E-mail empresarial',
                        'type' => 'email',
                        'placeholder' => 'contato@b13company.com',
                        'maxlenghtRoute' => 70,
                        'required' => false,
                        'id' => 'email',
                        'name' => 'email',
                        'function' => false,
                    ],
                ],
            ],
        ]);
        return $data;
    }

    private function montarFormVeiculos($value = null)
    {
        $data = new Fluent([
            'pageInfo' => [
                'title' => $value ? 'Editar veículo' : 'Cadastrar veículo',
                'form_action' => '',
                'form_method' => '',
                'label_button' => $value ? 'Editar veículo' : 'Cadastrar veículo',
                'dados_bancarios' => false,
                'cadastro_contatos' => false,
                'cadastro_adicionais' => true,
                'cadastro_especializacoes' => false,
                'cadastro_servicos' => true,
            ],
            'sessions' => [
                'Dados do Veículo' => [
                    'tipo' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-4',
                        'label' => 'Tipo do veículo',
                        'type' => 'select',
                        'placeholder' => '',
                        'route' => 'TipoVeiculoController',
                        'required' => false,
                        'id' => 'tipo',
                        'name' => 'tipo',
                        'function' => false,
                        'value' => $value['tipo'] ?? null,
                    ],
                    'categoria' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-4',
                        'label' => 'Categoria',
                        'type' => 'select',
                        'placeholder' => '',
                        'route' => 'CategoriaController',
                        'required' => false,
                        'id' => 'categoria',
                        'name' => 'categoria',
                        'function' => false,
                        'value' => $value['categoria'] ?? null,
                    ],
                    'marca' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-4',
                        'label' => 'Marca',
                        'type' => 'select',
                        'placeholder' => '',
                        'route' => 'MarcaController',
                        'required' => false,
                        'id' => 'marca',
                        'name' => 'marca',
                        'function' => false,
                        'value' => $value['marca'] ?? null,
                    ],
                    'ano' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-3',
                        'label' => 'Ano',
                        'type' => 'number',
                        'placeholder' => '',
                        'maxlenghtRoute' => 4,
                        'required' => false,
                        'id' => 'ano',
                        'name' => 'ano',
                        'function' => false,
                        'value' => $value['ano'] ?? null,
                    ],
                    'blindado' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-3',
                        'label' => 'Blindado',
                        'type' => 'select',
                        'placeholder' => '',
                        'route' => 'MarcaController',
                        'required' => false,
                        'id' => 'blindado',
                        'name' => 'blindado',
                        'function' => false,
                        'value' => $value['blindado'] ?? null,
                    ],
                    'passageiros' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-3',
                        'label' => 'Passageiros',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => '',
                        'required' => false,
                        'id' => 'passageiros',
                        'name' => 'passageiros',
                        'function' => false,
                        'value' => $value['passageiros'] ?? null,
                    ],
                    'malas' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-3',
                        'label' => 'Malas',
                        'type' => 'number',
                        'placeholder' => '',
                        'maxlenghtRoute' => '',
                        'required' => false,
                        'id' => 'malas',
                        'name' => 'malas',
                        'function' => false,
                        'value' => $value['malas'] ?? null,
                    ],
                    'data_vencimento' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-3',
                        'label' => 'Data de Vencimmento',
                        'type' => 'date',
                        'placeholder' => '',
                        'maxlenghtRoute' => '',
                        'required' => false,
                        'id' => 'data_vencimento',
                        'name' => 'data_vencimento',
                        'function' => false,
                        'value' => $value['data_vencimento'] ?? null,
                    ],
                    'placa' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-3',
                        'label' => 'Placa',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 8,
                        'required' => false,
                        'id' => 'placa',
                        'name' => 'placa',
                        'function' => false,
                        'value' => $value['placa'] ?? null,
                    ],
                    'seguro' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-3',
                        'label' => 'Seguro',
                        'type' => 'date',
                        'placeholder' => '',
                        'maxlenghtRoute' => 40,
                        'required' => false,
                        'id' => 'seguro',
                        'name' => 'seguro',
                        'function' => false,
                        'value' => $value['seguro'] ?? null,
                    ],
                    'parceira' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-3',
                        'label' => 'Empresa',
                        'type' => 'select',
                        'placeholder' => '',
                        'route' => 'EmpresasController',
                        'required' => false,
                        'id' => 'parceira',
                        'name' => 'parceira',
                        'function' => false,
                        'value' => $value['parceira'] ?? null,
                    ],
                    // 'imagem' => [
                    //     'container_tag' => 'div',
                    //     'container_class' => 'col-md-4 offset-md-4',
                    //     'label' => 'Foto do veículo',
                    //     'type' => 'file',
                    //     'placeholder' => 'Foto do veículo',
                    //     'maxlenghtRoute' => '',
                    //     'required' => false,
                    //     'id' => 'imagem',
                    //     'name' => 'imagem',
                    //     'function' => false,
                    //     'value' => $value['imagem'] ?? null,
                    // ],
                    'foto' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-3',
                        'label' => 'Foto',
                        'type' => 'file',
                        'class' => 'filepond',
                        'placeholder' => '',
                        'maxlenghtRoute' => '',
                        'required' => false,
                        'id' => 'foto',
                        'name' => 'foto',
                        'function' => false,
                        'value' => $value['foto'] ?? null,
                    ],
                    'documento' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-4',
                        'label' => 'Foto do documento',
                        'type' => 'file',
                        'placeholder' => 'Foto do documento',
                        'maxlenghtRoute' => '',
                        'required' => false,
                        'id' => 'documento',
                        'name' => 'documento',
                        'function' => false,
                        'value' => $value['documento'] ?? null,
                    ],
                ],
            ],
        ]);
        return $data;
    }

    private function montarFormEspecializacao($value = null)
    {
        $data = new Fluent([
            'pageInfo' => [
                'title' => $value ? 'Editar Especialização' : 'Cadastrar Especialização',
                'form_action' => '',
                'form_method' => '',
                'label_button' => $value ? 'Editar Especialização' : 'Cadastrar Especialização',
                //Aqui a ideia é passar um array com todos os dados bancários e montar ele no formBank
                'dados_bancarios' => false,
                'cadastro_contatos' => false,
                'cadastro_adicionais' => false,
                'cadastro_especializacoes' => false,
                'cadastro_servicos' => true,
            ],
            'sessions' => [
                'Cadastrar especialização' => [
                    'Nome' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-12',
                        'label' => 'Nome',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 50,
                        'required' => false,
                        'id' => 'nome',
                        'name' => 'nome',
                        'function' => false,
                        'dado' => $value['nome'] ?? null,
                    ],
                    'Name in English' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-12',
                        'label' => 'Name in English',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 70,
                        'required' => false,
                        'id' => 'name_english',
                        'name' => 'name_english',
                        'function' => false,
                        'dado' => $value['name_english'] ?? null,
                    ],
                    'Descrição' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-12',
                        'label' => 'Descrição',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 70,
                        'required' => false,
                        'id' => 'descricao',
                        'name' => 'descricao',
                        'function' => false,
                        'dado' => $value['descricao'] ?? null,
                    ],
                    'especializacoes' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-12',
                        'label' => 'Especialiazação ascendente',
                        'type' => 'select',
                        'placeholder' => '',
                        'route' => 'EspecializacoesController',
                        'required' => false,
                        'id' => 'especializacao',
                        'name' => 'especializacao',
                        'function' => false,
                        'value' => $value['especializacao'] ?? null,
                    ],
                ],
            ],
        ]);
        return $data;
    }

    private function montarFormAdicionais($value = null)
    {
        $data = new Fluent([
            'pageInfo' => [
                'title' => $value ? 'Editar Adicional' : 'Cadastrar Adicional',
                'form_action' => '',
                'form_method' => '',
                'label_button' => $value ? 'Editar Adicional' : 'Cadastrar Adicional',
                'dados_bancarios' => false,
                'cadastro_contatos' => false,
                'cadastro_adicionais' => false,
                'cadastro_especializacoes' => false,
                'cadastro_servicos' => true,
            ],
            'sessions' => [
                'Cadastrar Adicional' => [
                    'Nome' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-12',
                        'label' => 'Nome',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 50,
                        'required' => false,
                        'id' => 'nome',
                        'name' => 'nome',
                        'function' => false,
                        'dado' => $value['nome'] ?? null,
                    ],
                    'Name in English' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-12',
                        'label' => 'Name in English',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 70,
                        'required' => false,
                        'id' => 'name_english',
                        'name' => 'name_english',
                        'function' => false,
                        'dado' => $value['name_english'] ?? null,
                    ],
                    'Descrição' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-12',
                        'label' => 'Descrição',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 70,
                        'required' => false,
                        'id' => 'descricao',
                        'name' => 'descricao',
                        'function' => false,
                        'dado' => $value['descricao'] ?? null,
                    ],
                ],
            ],
        ]);
        return $data;
    }

    private function montarFormCategorias($value = null)
    {
        $data = new Fluent([
            'pageInfo' => [
                'title' => $value ? 'Editar Categoria' : 'Cadastrar Categoria',
                'form_action' => '',
                'form_method' => '',
                'label_button' => $value ? 'Editar Categoria' : 'Cadastrar Categoria',
                'dados_bancarios' => false,
                'cadastro_contatos' => false,
                'cadastro_adicionais' => false,
                'cadastro_especializacoes' => false,
                'cadastro_servicos' => true,
            ],
            'sessions' => [
                'Cadastrar Categoria' => [
                    'Nome' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-12',
                        'label' => 'Nome',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 50,
                        'required' => false,
                        'id' => 'nome',
                        'name' => 'nome',
                        'function' => false,
                        'dado' => $value['nome'] ?? null,
                    ],
                    'Name in English' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-12',
                        'label' => 'Name in English',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 70,
                        'required' => false,
                        'id' => 'name_english',
                        'name' => 'name_english',
                        'function' => false,
                        'dado' => $value['name_english'] ?? null,
                    ],
                    'Descrição' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-12',
                        'label' => 'Descrição',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 70,
                        'required' => false,
                        'id' => 'descricao',
                        'name' => 'descricao',
                        'function' => false,
                        'dado' => $value['descricao'] ?? null,
                    ],
                ],
            ],
        ]);
        return $data;
    }

    private function montarFormCategoriasServicos($value = null)
    {
        $data = new Fluent([
            'pageInfo' => [
                'title' => $value ? 'Editar Categoria' : 'Cadastrar Categoria',
                'form_action' => '',
                'form_method' => '',
                'label_button' => $value ? 'Editar Categoria' : 'Cadastrar Categoria',
                'dados_bancarios' => false,
                'cadastro_contatos' => false,
                'cadastro_adicionais' => false,
                'cadastro_especializacoes' => false,
                'cadastro_servicos' => true,
            ],
            'sessions' => [
                'Categoria de Serviço' => [
                    'Nome' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-12',
                        'label' => 'Nome',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 50,
                        'required' => false,
                        'id' => 'nome',
                        'name' => 'nome',
                        'function' => false,
                        'dado' => $value['nome'] ?? null,
                    ],
                    'Name in English' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-12',
                        'label' => 'Name in English',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 70,
                        'required' => false,
                        'id' => 'name_english',
                        'name' => 'name_english',
                        'function' => false,
                        'dado' => $value['name_english'] ?? null,
                    ],
                ],
            ],
        ]);
        return $data;
    }

    private function montarFormMotoristas($value = null)
    {
        $data = new Fluent([
            'pageInfo' => [
                'title' => $value ? 'Editar motorista' : 'Cadastrar motorista',
                'form_action' => '',
                'form_method' => '',
                'label_button' => $value ? 'Editar motorista' : 'Cadastrar motorista',
                'dados_bancarios' => true,
                'cadastro_contatos' => false,
                'cadastro_adicionais' => false,
                'cadastro_especializacoes' => true,
                'cadastro_servicos' => true,
            ],
            'sessions' => [
                'Dados da Empresa' => [
                    'foto' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-3',
                        'label' => 'Foto',
                        'type' => 'file',
                        'class' => 'filepond',
                        'placeholder' => '',
                        'maxlenghtRoute' => '',
                        'required' => false,
                        'id' => 'foto',
                        'name' => 'foto',
                        'function' => false,
                        'value' => $value['foto'] ?? null,
                    ],
                    'cpf' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-6',
                        'label' => 'CPF/CNPJ',
                        'type' => 'text',
                        'placeholder' => '00.000.000/0001-00',
                        'maxlenghtRoute' => 18,
                        'required' => false,
                        'id' => 'cpfcnpj',
                        'name' => 'cpfcnpj',
                        'function' => false,
                        'value' => $value['cpf'] ?? null,
                    ],
                    'apelido' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-6',
                        'label' => 'Apelido',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 50,
                        'required' => false,
                        'id' => 'apelido',
                        'name' => 'apelido',
                        'function' => false,
                        'value' => $value['apelido'] ?? null,
                    ],
                    'razao_social' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-6',
                        'label' => 'Razão Social',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 70,
                        'required' => false,
                        'id' => 'razao',
                        'name' => 'razao',
                        'function' => false,
                        'value' => $value['razao_social'] ?? null,
                    ],
                    'nome_fantasia' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-6',
                        'label' => 'Nome Fantasia',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 70,
                        'required' => false,
                        'id' => 'nome_fantasia',
                        'name' => 'nome_fantasia',
                        'function' => false,
                        'value' => $value['nome_fantasia'] ?? null,
                    ],
                    'cep' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-3',
                        'label' => 'CEP',
                        'type' => 'number',
                        'placeholder' => '00000-000',
                        'maxlenghtRoute' => 9,
                        'required' => false,
                        'id' => 'cep',
                        'name' => 'cep',
                        'function' => [
                            'type' => 'onblur',
                            'name' => 'pesquisaCep(this.value)',
                        ],
                        'value' => $value['cep'] ?? null,
                    ],
                    'logradouro' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-7',
                        'label' => 'Logradouro',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 50,
                        'required' => false,
                        'id' => 'logradouro',
                        'name' => 'logradouro',
                        'function' => false,
                        'value' => $value['logradouro'] ?? null,
                    ],
                    'numero' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-2',
                        'label' => 'Número',
                        'type' => 'number',
                        'placeholder' => '123',
                        'maxlenghtRoute' => 10,
                        'required' => false,
                        'id' => 'numero',
                        'name' => 'numero',
                        'function' => false,
                        'value' => $value['numero'] ?? null,
                    ],
                    'bairro' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-4',
                        'label' => 'Bairro',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 30,
                        'required' => false,
                        'id' => 'bairro',
                        'name' => 'bairro',
                        'function' => false,
                        'value' => $value['bairro'] ?? null,
                    ],
                    'cidade' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-4',
                        'label' => 'Cidade',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 40,
                        'required' => false,
                        'id' => 'cidade',
                        'name' => 'cidade',
                        'function' => false,
                        'value' => $value['cidade'] ?? null,
                    ],
                    'estado' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-2',
                        'label' => 'Estado',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 2,
                        'required' => false,
                        'id' => 'estado',
                        'name' => 'estado',
                        'function' => false,
                        'value' => $value['estado'] ?? null,
                    ],
                    'pais' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-2',
                        'label' => 'País',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 15,
                        'required' => false,
                        'placeholder' => '',
                        'id' => 'pais',
                        'name' => 'pais',
                        'function' => false,
                        'value' => $value['pais'] ?? null,
                    ],
                    'parceira' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-4',
                        'label' => 'Empresa',
                        'type' => 'select',
                        'placeholder' => '',
                        'route' => 'EmpresasController',
                        'required' => false,
                        'id' => 'parceira',
                        'name' => 'parceira',
                        'function' => false,
                        'value' => $value['parceira'] ?? null,
                    ],
                    'observacao' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-5',
                        'label' => 'Observação',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => '',
                        'required' => false,
                        'placeholder' => '',
                        'id' => 'observacao',
                        'name' => 'observacao',
                        'function' => false,
                        'value' => $value['observacao'] ?? null,
                    ],
                    'cnh' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-3',
                        'label' => 'Foto CNH',
                        'type' => 'file',
                        'placeholder' => '',
                        'maxlenghtRoute' => '',
                        'required' => false,
                        'id' => 'cnh',
                        'name' => 'cnh',
                        'function' => false,
                        'value' => $value['cnh'] ?? null,
                    ]
                ],
                'Contatos da Empresa' => [
                    'phone' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-4',
                        'label' => 'Telefone empresarial',
                        'type' => 'number',
                        'placeholder' => '(00)0000-00000',
                        'maxlenghtRoute' => 14,
                        'required' => false,
                        'id' => 'phone',
                        'name' => 'phone',
                        'function' => false,
                    ],
                    'email' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-8',
                        'label' => 'E-mail empresarial',
                        'type' => 'email',
                        'placeholder' => 'contato@b13company.com',
                        'maxlenghtRoute' => 70,
                        'required' => false,
                        'id' => 'email',
                        'name' => 'email',
                        'function' => false,
                    ],
                ],
            ],
        ]);
        return $data;
    }

    private function montarFormSegurancas($value = null)
    {
        $data = new Fluent([
            'pageInfo' => [
                'title' => $value ? 'Editar segurança' : 'Cadastrar segurança',
                'form_action' => '',
                'form_method' => '',
                'label_button' => $value ? 'Editar segurança' : 'Cadastrar segurança',
                'dados_bancarios' => true,
                'cadastro_contatos' => false,
                'cadastro_adicionais' => false,
                'cadastro_especializacoes' => true,
                'cadastro_servicos' => true,
            ],
            'sessions' => [
                'Dados da Empresa' => [
                    'foto' => [
                        'class' => 'filepond',
                        'container_tag' => 'div',
                        'container_class' => 'col-md-3',
                        'label' => 'Foto',
                        'type' => 'file',
                        'placeholder' => '',
                        'maxlenghtRoute' => '',
                        'required' => false,
                        'id' => 'foto',
                        'name' => 'foto',
                        'function' => false,
                        'value' => $value['foto'] ?? null,
                    ],
                    'cpf' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-6',
                        'label' => 'CPF/CNPJ',
                        'type' => 'text',
                        'placeholder' => '00.000.000/0001-00',
                        'maxlenghtRoute' => 18,
                        'required' => false,
                        'id' => 'cpfcnpj',
                        'name' => 'cpfcnpj',
                        'function' => false,
                        'value' => $value['cpf'] ?? null,
                    ],
                    'apelido' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-6',
                        'label' => 'Apelido',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 50,
                        'required' => false,
                        'id' => 'apelido',
                        'name' => 'apelido',
                        'function' => false,
                        'value' => $value['apelido'] ?? null,
                    ],
                    'razao_social' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-6',
                        'label' => 'Razão Social',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 70,
                        'required' => false,
                        'id' => 'razao',
                        'name' => 'razao',
                        'function' => false,
                        'value' => $value['razao_social'] ?? null,
                    ],
                    'nome_fantasia' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-6',
                        'label' => 'Nome Fantasia',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 70,
                        'required' => false,
                        'id' => 'nome_fantasia',
                        'name' => 'nome_fantasia',
                        'function' => false,
                        'value' => $value['nome_fantasia'] ?? null,
                    ],
                    'cep' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-3',
                        'label' => 'CEP',
                        'type' => 'number',
                        'placeholder' => '00000-000',
                        'maxlenghtRoute' => 9,
                        'required' => false,
                        'id' => 'cep',
                        'name' => 'cep',
                        'function' => [
                            'type' => 'onblur',
                            'name' => 'pesquisaCep(this.value)',
                        ],
                        'value' => $value['cep'] ?? null,
                    ],
                    'logradouro' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-7',
                        'label' => 'Logradouro',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 50,
                        'required' => false,
                        'id' => 'logradouro',
                        'name' => 'logradouro',
                        'function' => false,
                        'value' => $value['logradouro'] ?? null,
                    ],
                    'numero' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-2',
                        'label' => 'Número',
                        'type' => 'number',
                        'placeholder' => '123',
                        'maxlenghtRoute' => 10,
                        'required' => false,
                        'id' => 'numero',
                        'name' => 'numero',
                        'function' => false,
                        'value' => $value['numero'] ?? null,
                    ],
                    'bairro' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-4',
                        'label' => 'Bairro',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 30,
                        'required' => false,
                        'id' => 'bairro',
                        'name' => 'bairro',
                        'function' => false,
                        'value' => $value['bairro'] ?? null,
                    ],
                    'cidade' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-4',
                        'label' => 'Cidade',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 40,
                        'required' => false,
                        'id' => 'cidade',
                        'name' => 'cidade',
                        'function' => false,
                        'value' => $value['cidade'] ?? null,
                    ],
                    'estado' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-2',
                        'label' => 'Estado',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 2,
                        'required' => false,
                        'id' => 'estado',
                        'name' => 'estado',
                        'function' => false,
                        'value' => $value['estado'] ?? null,
                    ],
                    'pais' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-2',
                        'label' => 'País',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => 15,
                        'required' => false,
                        'placeholder' => '',
                        'id' => 'pais',
                        'name' => 'pais',
                        'function' => false,
                        'value' => $value['pais'] ?? null,
                    ],
                    'parceira' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-3',
                        'label' => 'Empresa',
                        'type' => 'select',
                        'placeholder' => '',
                        'route' => 'EmpresasController',
                        'required' => false,
                        'id' => 'parceira',
                        'name' => 'parceira',
                        'function' => false,
                        'value' => $value['parceira'] ?? null,
                    ],
                    'armado' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-3',
                        'label' => 'Armado',
                        'type' => 'select',
                        'placeholder' => '',
                        'route' => 'MarcaController',
                        'required' => false,
                        'id' => 'armado',
                        'name' => 'armado',
                        'function' => false,
                        'value' => $value['armado'] ?? null,
                    ],
                    'observacao' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-6',
                        'label' => 'Observação',
                        'type' => 'text',
                        'placeholder' => '',
                        'maxlenghtRoute' => '',
                        'required' => false,
                        'placeholder' => '',
                        'id' => 'observacao',
                        'name' => 'observacao',
                        'function' => false,
                        'value' => $value['observacao'] ?? null,
                    ],
                    'cnh' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-6',
                        'label' => 'Foto CNH',
                        'type' => 'file',
                        'placeholder' => '',
                        'maxlenghtRoute' => '',
                        'required' => false,
                        'id' => 'cnh',
                        'name' => 'cnh',
                        'function' => false,
                        'value' => $value['cnh'] ?? null,
                    ],
                    'cnv' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-6',
                        'label' => 'Foto CNV',
                        'type' => 'file',
                        'placeholder' => '',
                        'maxlenghtRoute' => '',
                        'required' => false,
                        'id' => 'cnv',
                        'name' => 'cnv',
                        'function' => false,
                        'value' => $value['cnv'] ?? null,
                    ],
                ],
                'Contatos da Empresa' => [
                    'phone' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-4',
                        'label' => 'Telefone empresarial',
                        'type' => 'number',
                        'placeholder' => '(00)0000-00000',
                        'maxlenghtRoute' => 14,
                        'required' => false,
                        'id' => 'phone',
                        'name' => 'phone',
                        'function' => false,
                    ],
                    'email' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-8',
                        'label' => 'E-mail empresarial',
                        'type' => 'email',
                        'placeholder' => 'contato@b13company.com',
                        'maxlenghtRoute' => 70,
                        'required' => false,
                        'id' => 'email',
                        'name' => 'email',
                        'function' => false,
                    ],
                ],
            ],
        ]);
        return $data;
    }

    private function montarFormServicos($value = null)
    {
        $data = new Fluent([
            'pageInfo' => [
                'title' => $value ? 'Editar servico' : 'Cadastrar servico',
                'form_action' => '',
                'form_method' => '',
                'label_button' => $value ? 'Editar servico' : 'Cadastrar servico',
                'dados_bancarios' => false,
                'cadastro_contatos' => false,
                'cadastro_adicionais' => false,
                'cadastro_especializacoes' => false,
                'cadastro_servicos' => true,
            ],
            'sessions' => [
                'locacao' => [
                    'Identificacao' => [
                        'categoriaServico' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-3',
                            'label' => 'Categoria do Serviço',
                            'type' => 'select',
                            'placeholder' => '',
                            'route' => 'CategoriaServicoController',
                            'required' => false,
                            'id' => 'categoriaServico',
                            'name' => 'categoriaServico',
                            'function' => false,
                            'value' => $value['categoriaServico'] ?? null,
                        ],
                        'nome' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-3',
                            'label' => 'Nome do serviço',
                            'type' => 'text',
                            'placeholder' => '',
                            'maxlenghtRoute' => 40,
                            'required' => false,
                            'id' => 'nome',
                            'name' => 'nome',
                            'function' => false,
                            'value' => $value['nome'] ?? null,
                        ],
                        'categoria' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-2',
                            'label' => 'Categoria',
                            'type' => 'select',
                            'placeholder' => '',
                            'route' => 'CategoriaController',
                            'required' => false,
                            'id' => 'categoria',
                            'name' => 'categoria',
                            'function' => false,
                            'value' => $value['categoria'] ?? null,
                        ],
                        'tipo' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-2',
                            'label' => 'Tipo do veículo',
                            'type' => 'select',
                            'placeholder' => '',
                            'route' => 'TipoVeiculoController',
                            'required' => false,
                            'id' => 'tipo',
                            'name' => 'tipo',
                            'function' => false,
                            'value' => $value['tipo'] ?? null,
                        ],
                        'blindado' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-2',
                            'label' => 'Blindado',
                            'type' => 'select',
                            'placeholder' => '',
                            'route' => 'MarcaController',
                            'required' => false,
                            'id' => 'blindado',
                            'name' => 'blindado',
                            'function' => false,
                            'value' => $value['blindado'] ?? null,
                        ],
                    ],
                    'Cobranca' => [
                        'precoBase' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-3',
                            'label' => 'Preço franquia',
                            'type' => 'number',
                            'placeholder' => '500',
                            'maxlenghtRoute' => '',
                            'required' => false,
                            'id' => 'precoBase',
                            'name' => 'precoBase',
                            'function' => false,
                        ],
                        'horasBase' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-2',
                            'label' => 'Horas franquia',
                            'type' => 'number',
                            'placeholder' => '500',
                            'maxlenghtRoute' => '',
                            'required' => false,
                            'id' => 'horasBase',
                            'name' => 'horasBase',
                            'function' => false,
                        ],
                        'precoHoraExtra' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-3',
                            'label' => 'Preço hora extra',
                            'type' => 'number',
                            'placeholder' => '50',
                            'maxlenghtRoute' => '',
                            'required' => false,
                            'id' => 'precoHoraExtra',
                            'name' => 'precoHoraExtra',
                            'function' => false,
                        ],
                        'kmBase' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-2',
                            'label' => 'KM franquia',
                            'type' => 'number',
                            'placeholder' => '50',
                            'maxlenghtRoute' => '',
                            'required' => false,
                            'id' => 'kmBase',
                            'name' => 'kmBase',
                            'function' => false,
                        ],
                        'kmExtra' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-2',
                            'label' => 'KM Extra',
                            'type' => 'number',
                            'placeholder' => '50',
                            'maxlenghtRoute' => '',
                            'required' => false,
                            'id' => 'kmExtra',
                            'name' => 'kmExtra',
                            'function' => false,
                        ],
                    ],
                    'Custos' => [
                        'custoParceiro' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-2',
                            'label' => 'Custo Parceiro',
                            'type' => 'number',
                            'placeholder' => '300',
                            'maxlenghtRoute' => '',
                            'required' => false,
                            'id' => 'custoParceiro',
                            'name' => 'custoParceiro',
                            'function' => false,
                        ],
                        'horaExtraParceiro' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-3',
                            'label' => 'Hora extra parceiro',
                            'type' => 'number',
                            'placeholder' => '500',
                            'maxlenghtRoute' => '',
                            'required' => false,
                            'id' => 'horaExtraParceiro',
                            'name' => 'horaExtraParceiro',
                            'function' => false,
                        ],
                        'kmExtraParceiro' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-2',
                            'label' => 'KM extra parceiro',
                            'type' => 'number',
                            'placeholder' => '50',
                            'maxlenghtRoute' => '',
                            'required' => false,
                            'id' => 'kmExtraParceiro',
                            'name' => 'kmExtraParceiro',
                            'function' => false,
                        ],
                        'custoMotorista' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-2',
                            'label' => 'Custo motorista',
                            'type' => 'number',
                            'placeholder' => '250',
                            'maxlenghtRoute' => '',
                            'required' => false,
                            'id' => 'custoMotorista',
                            'name' => 'custoMotorista',
                            'function' => false,
                        ],
                        'custoMotoristaExtra' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-3',
                            'label' => 'Hora extra motorista',
                            'type' => 'number',
                            'placeholder' => '50',
                            'maxlenghtRoute' => '',
                            'required' => false,
                            'id' => 'custoMotoristaExtra',
                            'name' => 'custoMotoristaExtra',
                            'function' => false,
                        ],
                    ],
                ],
                'seguranca' => [
                    'Identificacao' => [
                        'categoriaServico' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-4',
                            'label' => 'Categoria do Serviço',
                            'type' => 'select',
                            'placeholder' => '',
                            'route' => 'CategoriaServicoController',
                            'required' => false,
                            'id' => 'categoriaServico',
                            'name' => 'categoriaServico',
                            'function' => false,
                            'value' => $value['categoriaServico'] ?? null,
                        ],
                        'nome' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-4',
                            'label' => 'Nome do serviço',
                            'type' => 'text',
                            'placeholder' => '',
                            'maxlenghtRoute' => 40,
                            'required' => false,
                            'id' => 'nome',
                            'name' => 'nome',
                            'function' => false,
                            'value' => $value['nome'] ?? null,
                        ],
                        'tipo' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-2',
                            'label' => 'Tipo do segurança',
                            'type' => 'select',
                            'placeholder' => '',
                            'route' => 'TipoSegurancaController',
                            'required' => false,
                            'id' => 'tipo',
                            'name' => 'tipo',
                            'function' => false,
                            'value' => $value['tipo'] ?? null,
                        ],
                        'armado' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-2',
                            'label' => 'Armado',
                            'type' => 'select',
                            'placeholder' => '',
                            'route' => 'MarcaController',
                            'required' => false,
                            'id' => 'armado',
                            'name' => 'armado',
                            'function' => false,
                            'value' => $value['armado'] ?? null,
                        ],
                    ],
                    'Cobranca' => [
                        'precoBase' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-4',
                            'label' => 'Preço franquia',
                            'type' => 'number',
                            'placeholder' => '500',
                            'maxlenghtRoute' => '',
                            'required' => false,
                            'id' => 'precoBase',
                            'name' => 'precoBase',
                            'function' => false,
                        ],
                        'horasBase' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-4',
                            'label' => 'Horas franquia',
                            'type' => 'number',
                            'placeholder' => '500',
                            'maxlenghtRoute' => '',
                            'required' => false,
                            'id' => 'horasBase',
                            'name' => 'horasBase',
                            'function' => false,
                        ],
                        'precoHoraExtra' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-4',
                            'label' => 'Preço hora extra',
                            'type' => 'number',
                            'placeholder' => '50',
                            'maxlenghtRoute' => '',
                            'required' => false,
                            'id' => 'precoHoraExtra',
                            'name' => 'precoHoraExtra',
                            'function' => false,
                        ],
                    ],
                    'Custos' => [
                        'custoParceiro' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-3',
                            'label' => 'Custo Parceiro',
                            'type' => 'number',
                            'placeholder' => '300',
                            'maxlenghtRoute' => '',
                            'required' => false,
                            'id' => 'custoParceiro',
                            'name' => 'custoParceiro',
                            'function' => false,
                        ],
                        'horaExtraParceiro' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-3',
                            'label' => 'Hora extra parceiro',
                            'type' => 'number',
                            'placeholder' => '500',
                            'maxlenghtRoute' => '',
                            'required' => false,
                            'id' => 'horaExtraParceiro',
                            'name' => 'horaExtraParceiro',
                            'function' => false,
                        ],
                        'custoSeguranca' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-3',
                            'label' => 'Custo segurança',
                            'type' => 'number',
                            'placeholder' => '250',
                            'maxlenghtRoute' => '',
                            'required' => false,
                            'id' => 'custoSeguranca',
                            'name' => 'custoSeguranca',
                            'function' => false,
                        ],
                        'custoSegurancaExtra' => [
                            'container_tag' => 'div',
                            'container_class' => 'col-md-3',
                            'label' => 'Hora extra segurança',
                            'type' => 'number',
                            'placeholder' => '50',
                            'maxlenghtRoute' => '',
                            'required' => false,
                            'id' => 'custoSegurancaExtra',
                            'name' => 'custoSegurancaExtra',
                            'function' => false,
                        ],
                    ],
                ]
            ],
        ]);
        return $data;
    }

    private function montarFormOrcamento($value = null)
    {
        $data = new Fluent([
            'pageInfo' => [
                'title' => $value ? 'Editar orçamento' : 'Cadastrar orçamento',
                'form_action' => '',
                'form_method' => '',
                'label_button' => $value ? 'Editar orçamento' : 'Cadastrar orçamento',
                'dados_bancarios' => false,
                'cadastro_contatos' => false,
                'cadastro_adicionais' => false,
                'cadastro_especializacoes' => false,
                'cadastro_servicos' => true,
            ],
            'sessions' => [
                'Dados do Cliente' => [
                    'cliente' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-6',
                        'label' => 'Cliente',
                        'type' => 'select',
                        'placeholder' => '',
                        'route' => 'ClientesController',
                        'required' => false,
                        'id' => 'cliente',
                        'name' => 'cliente',
                        'function' => false,
                        'value' => $value['cliente'] ?? null,
                    ],
                    'contato' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-6',
                        'label' => 'Contato',
                        'type' => 'select',
                        'placeholder' => '',
                        'route' => 'ClientesController',
                        'required' => false,
                        'id' => 'contato',
                        'name' => 'contato',
                        'function' => false,
                        'value' => $value['contato'] ?? null,
                    ],
                ]
            ]
        ]);

        return $data;
    }

    private function montarFormOS($value = null)
    {
        $data = new Fluent([
            'pageInfo' => [
                'title' => $value ? 'Editar OS' : 'Cadastrar OS',
                'form_action' => '',
                'form_method' => '',
                'label_button' => $value ? 'Editar OS' : 'Cadastrar OS',
                'dados_bancarios' => false,
                'cadastro_contatos' => false,
                'cadastro_adicionais' => false,
                'cadastro_especializacoes' => false,
                'cadastro_servicos' => true,
            ],
            'sessions' => [
                'Dados do Cliente' => [
                    'cliente' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-6',
                        'label' => 'Cliente',
                        'type' => 'select',
                        'placeholder' => '',
                        'route' => 'ClientesController',
                        'required' => false,
                        'id' => 'cliente',
                        'name' => 'cliente',
                        'function' => false,
                        'value' => $value['cliente'] ?? null,
                    ],
                    'contato' => [
                        'container_tag' => 'div',
                        'container_class' => 'col-md-6',
                        'label' => 'Contato',
                        'type' => 'select',
                        'placeholder' => '',
                        'route' => 'ClientesController',
                        'required' => false,
                        'id' => 'contato',
                        'name' => 'contato',
                        'function' => false,
                        'value' => $value['contato'] ?? null,
                    ],
                ]
            ]
        ]);

        return $data;
    }
}
